##hystrix:
##  command:
##    default:
##      execution:
##        isolation:
##          thread:
##            timeoutInMilliseconds: 212000
##            strategy: THREAD
##
##ribbon:
##  readTimeout: 60000
##  connection-timeout: 60000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#ribbon:
#  ReadTimeout: 60000
#  connection-timeout: 3000
#  eureka:
#    enabled: true
#zuul:
#  ignoredServices: '*'
#  host:
#    time-to-live: -1
#    connect-timeout-millis: 5000
#    max-per-route-connections: 10000
#    max-total-connections: 5000
#    socket-timeout-millis: 60000
#  semaphore:
#    max-semaphores: 500